### ISSUE TITLE
Add a Nav bar in this page.

### ISSUE THREAD

**Issue by harshit-46** [harshit-46/WebPage-Clone#1]
If anyone interested, add a new navigation bar at the top of the webpage.

**Comment by Atharvcreatives** [comment]
Hey Harshit, I would love to work on this, so can you assign this to me?

**Comment by harshit-46** [comment]
I am glad that you want to contribute to this you are welcome please go ahead I will definitely merge your pr if your changes seems to be better.

**Comment by harshit-46** [comment]
Assigned
